In [13]:
import pandas as pd
import numpy as np
import joblib
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, classification_report

print("All libraries imported successfully!")

All libraries imported successfully!

In [3]:
data = {
    "compatibility": [
        1, 1, 1, 1, 1,
        0, 0, 0, 1, 1,
        1, 1, 1, 0, 1,
        1, 0, 1, 1, 1
    ],

    "distance_km": [
        2, 5, 10, 15, 25,
        30, 50, 70, 8, 100,
        3, 12, 20, 60, 18,
        4, 80, 7, 35, 22
    ],

    "urgency": [
        3, 3, 2, 3, 2,
        3, 2, 3, 3, 1,
        3, 2, 2, 3, 2,
        3, 3, 2, 1, 2
    ],

    "same_location": [
        1, 1, 1, 0, 0,
        0, 0, 0, 1, 0,
        1, 1, 0, 0, 1,
        1, 0, 1, 0, 1
    ],

    "is_available": [
        1, 1, 1, 1, 1,
        1, 1, 1, 1, 1,
        1, 1, 1, 1, 1,
        1, 1, 1, 1, 1
    ],

    "suitable": [
        1, 1, 1, 1, 1,
        0, 0, 1, 1, 0,
        1, 1, 1, 0, 1,
        1, 0, 1, 0, 1
    ]
}

df = pd.DataFrame(data)

df

    compatibility  distance_km  urgency  same_location  is_available  suitable
0               1            2        3              1             1         1
1               1            5        3              1             1         1
2               1           10        2              1             1         1
3               1           15        3              0             1         1
4               1           25        2              0             1         1
5               0           30        3              0             1         0
6               0           50        2              0             1         0
7               0           70        3              0             1         1
8               1            8        3              1             1         1
9               1          100        1              0             1         0
10              1            3        3              1             1         1
11              1           12        2              1             1         1
12              1           20        2              0             1         1
13              0           60        3              0             1         0
14              1           18        2              1             1         1
15              1            4        3              1             1         1
16              0           80        3              0             1         0
17              1            7        2              1             1         1
18              1           35        1              0             1         0
19              1           22        2              1             1         1

In [4]:
# Select input features
X = df[
    [
        "compatibility",
        "distance_km",
        "urgency",
        "same_location",
        "is_available"
    ]
]

# Select target
y = df["suitable"]

print("Features (X):")
display(X)

print("Target (y):")
display(y)

Features (X):

    compatibility  distance_km  urgency  same_location  is_available
0               1            2        3              1             1
1               1            5        3              1             1
2               1           10        2              1             1
3               1           15        3              0             1
4               1           25        2              0             1
5               0           30        3              0             1
6               0           50        2              0             1
7               0           70        3              0             1
8               1            8        3              1             1
9               1          100        1              0             1
10              1            3        3              1             1
11              1           12        2              1             1
12              1           20        2              0             1
13              0           60        3              0             1
14              1           18        2              1             1
15              1            4        3              1             1
16              0           80        3              0             1
17              1            7        2              1             1
18              1           35        1              0             1
19              1           22        2              1             1

Target (y):

0     1
1     1
2     1
3     1
4     1
5     0
6     0
7     1
8     1
9     0
10    1
11    1
12    1
13    0
14    1
15    1
16    0
17    1
18    0
19    1
Name: suitable, dtype: int64

In [5]:
# Split the dataset into training and testing data

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42
)

print("Training samples:", len(X_train))
print("Testing samples:", len(X_test))

Training samples: 16
Testing samples: 4

In [7]:
# Create the Random Forest model

model = RandomForestClassifier(
    n_estimators=100,
    random_state=42
)

# Train the model
model.fit(X_train, y_train)

print("AI model trained successfully! ")

AI model trained successfully!

In [8]:
# Make predictions on the testing data

y_pred = model.predict(X_test)

print("Actual values:   ", list(y_test))
print("Predicted values:", list(y_pred))

Actual values:    [1, 1, 1, 1]
Predicted values: [np.int64(1), np.int64(1), np.int64(1), np.int64(1)]

In [9]:
accuracy = accuracy_score(y_test, y_pred)
print("Model Accuracy:" , round(accuracy * 100 , 2),"%")

Model Accuracy: 100.0 %

In [11]:
print(classification_report(y_test, y_pred, zero_division=0))

              precision    recall  f1-score   support

           1       1.00      1.00      1.00         4

    accuracy                           1.00         4
   macro avg       1.00      1.00      1.00         4
weighted avg       1.00      1.00      1.00         4

In [12]:
# Test the AI model with a new donor

new_donor = pd.DataFrame({
    "compatibility": [1],
    "distance_km": [8],
    "urgency": [3],
    "same_location": [1],
    "is_available": [1]
})

prediction = model.predict(new_donor)

if prediction[0] == 1:
    print("AI Prediction: Suitable Donor ✅")
else:
    print("AI Prediction: Not Suitable Donor ❌")

AI Prediction: Suitable Donor ✅

In [14]:
joblib.dump(model,"blood_donor_model.pkl")

['blood_donor_model.pkl']